### ISSUE TITLE
Visual Studio 2019 version and Tests issue

### ISSUE THREAD

**Issue by jolgri** [DeborahK/CSharpBP-Basics#1] opened 2020-05-10 10:16 UTC
Dear Deborah, 

I like your courses very much.  However, it seems there is an issue , which occurs in Visual Studio 2019. There is demo: Buiding a class demo in the chapter  #4. And at video time 3:34 you show how to perform and run tests (Create Unit test). However, it does  not work in Visual Studio 2019, because there is no 'Run test' option. I can get the 'test explorer' window , but not able to run the tests, because it seems *.cs type files is not possible to add to the playlist of the Test Explorer. Most likely something very simple, but it seems from discussions on Pluralsight webpage other participants also were struggling with it. Your help would be appreciated, 
![Pluralsight_1](https://user-images.githubusercontent.com/54156179/81496412-d812c280-92b7-11ea-8c07-21ed14e15100.JPG)
![Pluralsight_2_VS2019 scren no files added](https://user-images.githubusercontent.com/54156179/81496420-dfd26700-92b7-11ea-8818-09377be16039.JPG)

Have a nice week, 
Jolanta

**Comment by DeborahK** [comment] 2020-05-10 14:51
Thank you for the kind words about the course.

I just re-downloaded the code and opened it in Visual Studio 2019. Without doing anything (no compile, no run options) I see this:

![image](https://user-images.githubusercontent.com/7987365/81502311-12696900-9292-11ea-86de-43ba1b24e509.png)

Dropping doen the Arrow button, I see this:
![image](https://user-images.githubusercontent.com/7987365/81502334-2ca34700-9292-11ea-9178-32fe1fc92610.png)

Checking the Pluralsight page for the course, I don't see any other posts regarding this issue?

Sometimes, it does take a moment for Visual Studio to find the tests. A few suggestions:
1) Try a full recompile.
2) Try existing Visual Studio and opening it again.

If neither of those help, could you post a screen shot of your Test Explorer window?

**Comment by jolgri** [comment] 2020-05-10 17:28
Dear Deborah, 
Thank you for the answer. It seems specific extension is needed to Visual Studio 2019 that it would be possible to run the tests. Please find attached the page view. The tests are not found on the TestExplorer. 
Best regards, 
Jolanta

![image](https://user-images.githubusercontent.com/54156179/81506034-fb5b6300-92f3-11ea-90c6-24fbd570e76a.png)

**Comment by DeborahK** [comment] 2020-05-10 17:36
These are the only extensions I have installed in my VS 2019

![image](https://user-images.githubusercontent.com/7987365/81506274-0be6eb80-92aa-11ea-946b-2c4b34643cf6.png)

**Comment by DeborahK** [comment] 2020-05-10 17:38
But I do have a reference to the unit testing framework:

![image](https://user-images.githubusercontent.com/7987365/81506324-59fbef00-92aa-11ea-9d40-4bdc4f8af3b5.png)

**Comment by jolgri** [comment] 2020-05-10 21:23
Dear Deborah, 
Thank you for the answers. I have re-installed the Visual Studio with the same packages as yours. However, there is no longer available Microsoft. VisualStudio.QualityTools. UnitTestFramework. 
Best regards, 
Jolanta

**Comment by DeborahK** [comment] 2020-05-11 14:30
The only other thing I could suggest would be to try to build a test from scratch and see if that loads the libraries you need. Both my "C# OOP" course: https://app.pluralsight.com/library/courses/object-oriented-programming-fundamentals-csharp

and my "Defensive Development in C#" course: https://app.pluralsight.com/library/courses/csharp-defensive-coding (though this one uses a different testing library)

Were recently updated and show the steps for creating a unit test project from scratch in VS 2019.

Other than this, I have no further ideas. I would have assumed that loading the project would have loaded any of the libraries that it needed.

**Comment by jolgri** [comment] 2020-05-11 14:35
Dear Deborah, 
Thank you for the excellent suggestions. 
Have a wonderful week, 
Best regards, 
Jolanta

**Comment by blex244** [comment] 2020-05-13 21:16
The solution is here:
https://developercommunity.visualstudio.com/content/problem/833631/there-is-a-missing-project-subtype-3ac096d0-a1c2-e.html

Solution by Filip Masset   Feb 05 at 01:12 PM

I got this solved by enabling the extension "**Developer Analytics Tools" in Extensions -> Manage Extensions -> Installed**. When an extension crashes, Visual Studio asks to disable it the next time, but it seems that this one causes issues with the MSTest projects.

**Comment by DeborahK** [comment] 2020-05-13 23:44
As it looks like the issue is defined above, I'm closing this.

Thanks!

**Closed as completed by DeborahK** 2020-05-13 23:44 UTC
